server:  
  port: ${PORT:8889}
    
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        monitor:
          gitlab:
            enabled: true
        git:
          cloneOnStart: true
          uri: https://github.com/michaelzhou2016/sample-config-repo.git
          username: michaelzhou2016
          password: password
          search-paths: /,sample-client-service,sample-server-service
  profiles:
    active: dev

---
spring:
  profiles: dev
  rabbitmq:
    host: 10.139.60.131:5672
    port: 5672
    username: kkuser
    password: kkuser123
  cloud:
    bus:
      trace:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

---
spring:
  profiles: production                            # 指定profile=production
  cloud:
    bus:
      trace:
        enabled: true     # 开启cloud bus的跟踪
  rabbitmq:               # 使用rabbitmq
    username: rabbitadmin
    password: rabbitadmin
    addresses: 10.10.17.35:5672,10.10.17.18:5672,10.10.16.76:5672
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/ # 配置服务中心地址
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh